travis:
  secure:
    BINSTAR_TOKEN: acNXnt3ou8uZLlXullgjzWftOwFuIUw70C3bvSHK4hsZMDzA4ZZprA//B74N1K2CcNm7fqM4aZUmw8aBIxuOrdCYQlqqNOg/zdoXB9cPSIzFR4vkhfnK7EX/Uf/xtoiPqWHI0ikN3MzM8Re82+ziOHUjemZXft2LC9yeEpeqd1tnj9Nl8QUj6aiQ7poRMqmpOEouV0nD2MXj7MJLaCU+bgZpcL1CAokeDrjZRvfMgnKsbuT5fe3oLkIYVN6dRVmasSoxqaf01lip180nvTar7PnN7jQmJtw6YvIVALTSkVvU1h0o2nirEAxzua/0f3N/BxBJMD3ErsWuiZ4+OkZ2yWHqnYqW++7AC1+Dm/UlF45S3m8F1X2uktgOL41BMbgHAVFANpKXi6HWpa7b9zQCOMGhxmyV+BgraWRd5wHNsGsuVwzwncefURdtYNbD96jIA6HrDW265kerb9TnWD/h5RcfNGUFQ9iUFYSJMnjlyO2UaCFKkv2lxvG/1WWCNGyxSGaHkrzk5zVLqXVsofdwLjfSif01CeNaIYdpUb7m2+0+FDF09rItlm2hFn5D/rTw1HKMzj/U+xvm8jVs5dM+HZ5dNWtxQnRHISX041MiiBkICv6q/QSNrseMEp9Ssd+938CFUsHgfXS/c4T356Nbw7QZoULWJY826pT6EU5tqRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
